//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registy.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSpecializations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonSpecializations()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int id { get; set; }
        public Nullable<int> specId { get; set; }
        public Nullable<long> personId { get; set; }
        public int workTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Persons Persons { get; set; }
        public virtual Specializations Specializations { get; set; }
    }
}
