//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registy.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdecuresToShedule
    {
        public int id { get; set; }
        public Nullable<int> procId { get; set; }
        public Nullable<int> sheduleId { get; set; }
    
        public virtual ProcedureNames ProcedureNames { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
