//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registy.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int id { get; set; }
        public long pipn { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int orderId { get; set; }
    
        public virtual PersonSpecializations PersonSpecializations { get; set; }
    }
}
